services:
  consul:
    build:
      context: ./consul # Path to the Dockerfile directory
      dockerfile: Dockerfile
    container_name: consul
    ports:
      - "8500:8500" # Expose Consul's HTTP API and Web UI
      - "8600:8600/udp" # Expose Consul's DNS interface
    volumes:
      - consul_data:/consul/data # Persist Consul's data
    networks:
      - consul_network

  vault:
    build:
      context: ./vault # Path to the Dockerfile directory
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200" # Expose Vault API and Web UI
    environment:
      VAULT_ADDR: "https://127.0.0.1:8200" # Vault server address
    volumes:
      - ./vault/config:/vault/config # Mount Vault configuration
      - ./vault/certs:/vault/certs # Mount certificates
      - ./vault/data:/vault/data # Persist Vault storage
    cap_add:
      - IPC_LOCK # Required to lock memory (security reason)
    restart: unless-stopped
    networks:
      - consul_network
networks:
  consul_network:
    driver: bridge # Use the default bridge network driver for communication
volumes:
  consul_data:
