apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: anderalextu/allegro-clone-consul:latest  # Replace with your custom Consul image
          ports:
          - containerPort: 8500
          - containerPort: 8600
            protocol: UDP
          volumeMounts:
          - name: consul-data
            mountPath: /consul/data # Inside the container
      volumes:
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
    - protocol: TCP
      port: 8500  # Expose the UI/API port
      targetPort: 8500
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consul-ingress
spec:
  rules:
    - host: consul.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: consul
                port:
                  number: 8500
