apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true" # Enables sidecar injection for service mesh
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: anderalextu/allegro-clone-auth-service:latest # Replace with your container image
        ports:
        - containerPort: 5000 # Expose the application on port 5000
          name: http
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000" # Bind the app to all network interfaces
