apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: auth-service
  namespace: default
# Allow traffic from nginx to frontend
spec:
  destination:
    name: auth-service
  sources:
    - name: nginx
      action: allow